### ISSUE TITLE
[Feature]: add ACC to the state machine

### ISSUE THREAD

**Issue by JoKircher** [ll7/paf22#117]
### Description

The acting team has an ACC as integral part of their concept. This needs to be incorporated in the state machine. To further unterstand the topic a couple of information are necessary from the acting team. 

* How should the ACC work exactly?
* In which situations should the ACC be turned on and off?
* What happens if there is no leading vehicle?
* What happens if the target speed changes and is lower than the speed needed to keep the distance?
* What should happen if suddenly an obstacle between the vehicle in front of us and the ego vehicle appears?

### Definition of Done

complete the design of the state machine, find a suitable place to incorporate the ACC into the state machine.

**Comment by JoKircher** [comment]
@schwalga @Julian-Graf to properly unterstand the topic some information on the questions in the description would be great

**Comment by schwalga** [comment]
I will try to answer most questions, @Julian-Graf feel free to correct me/ add other things, as we haven't talked about the details yet.

- ACC is meant as an alternative mode for controlling the velocity of the vehicle (-> only longitudinal control).
- ACC should only be activated on relatively straight roads by the planning domain.
- It can then be deactivated within the acting domain if an error occurs (for example the vehicle in front switches lanes, or another vehicle changes onto our lane, thereby violating the safe distance, this would also be the category where your 4/5th point would come into play, ...)
- The planning domain might want to disable ACC ahead of corners, and intersections, ...

If you need additional info it might be easier to talk on Discord. 
@JoKircher  @Julian-Graf.

**Comment by Julian-Graf** [comment]
**What happens if the target speed changes and is lower than the speed needed to keep the distance?**
- The ACC will not drive faster than the target speed, it will only drive at target speed or slower than target speed. If the distance gets greater than wanted, the ACC will drive at target speed.

**In which situations should the ACC be turned on and off?**
Addition to Gabriels answer:
- The ACC should also work in curves. But it might cause problems if not turned off in tight curves and when making a turn.

**What happens if there is no leading vehicle?**
- If there is no distance to the leading vehicle published, the ACC can not be turned on. So if there is no vehicle in front, no distance to the vehicle in front should be published.

**What should happen if suddenly an obstacle between the vehicle in front of us and the ego vehicle appears?**
- If there is an unexpected situation, like a pedestrian entering the road, the acting can not detect this. The planning has to make sure to turn off the ACC in these cases.
- If the distance to the vehicle in front can't be measured reliably, it might be better to turn the ACC off. But as long as the distance is published, the ACC tries to optimize it.

**Note**:
In #33 we decided to put an ACC in the acting. If it turns out that keeping the distance to the leading vehicle is better done in the planning e.g. in the state machine, we can open this up for discussion again, as nothing is implemented yet.

**Comment by JoKircher** [comment]
As there is no state machine anymore, this issue is outdated
